syntax enable

filetype indent on
filetype plugin on

nnoremap <space> <nop>
let mapleader = " "

set autoindent
set autoread
set autowrite
set ignorecase
set laststatus=2
set lazyredraw
set maxmempattern=2000
set list listchars=tab:»·,trail:·
set nobackup
set noerrorbells
set noswapfile
set number
set relativenumber
set ruler
set smartcase
set ttyfast
set wildmenu

map <leader>x :e ~/t.md<cr>
map K <nop>
