# SPDX-FileCopyrightText: 2025 Daniel Morris <daniel@honestempire.com>
# SPDX-License-Identifier: MIT

autoload -U +X colors && colors
autoload -U +X compinit && compinit

export AWS_DEFAULT_REGION="eu-west-1"
export AWS_REGION="$AWS_DEFAULT_REGION"
export CLICOLOR="1"
export DISPLAY=":0"
export GOPATH="$HOME/go"
export GOPRIVATE="github.com/honestempire,github.com/unfunco"
export GPG_TTY="$(tty)"
export NVM_DIR="$HOME/.nvm"
export PROMPT="%(?.%F{71}0.%F{196}%?)%f %F{214}%1~%f %F{244}→%f "

alias headers="curl -sSL -D - $1 -o /dev/null"
alias hist="history 1"
alias ip="curl https://checkip.amazonaws.com 2>/dev/null"
alias k="kubectl"
alias l="ls -laht"
alias md="mkdir -p"

export PATH="$PATH:$GOPATH/bin"

for cfg in "$HOME/.zsh/configs"/*.zsh; do
  source $cfg
done

for fn in "$HOME/.zsh/functions"/*.zsh; do
  source $fn
done

source <(kubectl completion zsh)
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(rbenv init - zsh)"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
