# Copyright © 2016 Daniel Morris
# https://unfun.co
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

autoload -U +X colors && colors
autoload -U +X compinit && compinit

export AZURE_CORE_COLLECT_TELEMETRY=false
export AWS_DEFAULT_REGION=eu-west-2
export CLICOLOR=1
export GOPRIVATE="github.com/honestempire,github.com/unfunco"
export GPG_TTY=$(tty)
export PROMPT="%(?.%F{71}0.%F{196}%?)%f %F{214}%1~%f $ "
export SAM_CLI_TELEMETRY=0

alias headers="curl -sSL -D - $1 -o /dev/null"
alias hist="history 1"
alias ip="curl https://checkip.amazonaws.com 2>/dev/null"
alias k="kubectl"
alias md="mkdir -p"
alias t="vi ~/Desktop/t.md"

for c in "$HOME/.zsh/configs"/*.zsh; do
  . $z
done

for f in "$HOME/.zsh/functions"/*.zsh; do
  . $f
done

source <(kubectl completion zsh)
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
