name: CI

on:
  push:
    branches:
    - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Check shell scripts
      run: find . -type f \( -name '*.sh' \) | xargs shellcheck -x -s bash

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - name: Prepare the release
      uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
